/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2017-12-08 08:43:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cafterlogininformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/java/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/qqq/WEB-INF/lib/struts2-core-2.3.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1467851796000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.30.jar", Long.valueOf(1483621054000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\" ng-app='userInfoApp' ng-controller='userInfoCtrl'>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>我的资料 - 包满意 - 让靠谱的工程师为你开发 | 互联网软件众包平台</title>\r\n");
      out.write("    \t  \r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"\"><meta name=\"description\" content=\"\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/bootstrap.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/form.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/header.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/footer-simple.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/font-awesome/css/font-awesome.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jqueryvalidate/css/cmxform.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.placeholder.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/bootstrap.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/comm.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/jquery.validate.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/localization/messages_zh.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/public/register.css?v=201608241757\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/public/login.css?v=201608241757\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/public/login.js?v=201608241757\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://www.make8.com/css/bootstrap.min.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/css/footer.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/css/comm.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/css/helpdocker.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/font-awesome/css/font-awesome.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/thirdparty/jqueryvalidate/css/cmxform.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/thirdparty/jqueryconfirm/css/jquery-confirm.min.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/thirdparty/bootstrapdialog/css/bootstrap-dialog.min.css?v=201608241757\"  rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"https://www.make8.com/thirdparty/jquerypagination/css/jquery.pagination.css?v=201608241757\"  rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/jquery.min.js?v=201608241757\"></script>\r\n");
      out.write("   \t<script type=\"text/javascript\" src=\"https://www.make8.com/js/angular.min.js?v=201608241757\"></script>\r\n");
      out.write("   \t<script type=\"text/javascript\" src=\"https://www.make8.com/js/angular-route.min.js?v=201608241757\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.make8.com/js/angular-resource.min.js?v=201608241757\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.make8.com/js/angular-comm.js?v=201608241757\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.make8.com/js/map.js?v=201608241757\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.make8.com/js/jquery.placeholder.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/bootstrap.min.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/header.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/comm.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/footer.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/helpdocker.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/jqueryvalidate/js/jquery.validate.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/jqueryvalidate/js/localization/messages_zh.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/jqueryconfirm/js/jquery-confirm.min.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/bootstrapdialog/js/bootstrap-dialog.min.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/jquery-ui.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/jquerypagination/js/jquery.pagination-1.2.7.min.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t<link href=\"https://www.make8.com/thirdparty/countdown/css/jquery.countdown.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://www.make8.com/thirdparty/fileinput/css/fileinput.min.css?v=201608241757\"  rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"https://www.make8.com/thirdparty/datetimepicker/css/bootstrap-datetimepicker.css?v=201608241757\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/js/projectprogress.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/countdown/js/jquery.countdown.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/jqueryraty/jquery.raty.min.js?v=201608241757\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/fileinput/js/fileinput.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/fileinput/js/fileinput_locale_zh.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/datetimepicker/js/bootstrap-datetimepicker.js?v=201608241757\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.make8.com/thirdparty/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js?v=201608241757\"></script>\r\n");
      out.write(" \r\n");
      out.write("\t  <link rel=\"stylesheet\" href=\"https://www.make8.com/css/home/userinfo.css?v=201608241757\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("<!--start of header-->\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<a href=\"/\">\r\n");
      out.write("\t\t\t\t<img src=\"Images/logo.png\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Welcome\">首页</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"newDiv\"><a href=\"publish\">发布需求</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"projectall\">项目列表</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"stoplist\">优秀程序员</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aboutus\">关于我们</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"login_status\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"login\" class=\"btn login\" type=\"button\" onclick=\"javascript:location.href='login'\" value=\"登录\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"join\" class=\"btn join\" type=\"button\" onclick=\"javascript:location.href='register'\" value=\"注册\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!--end of header-->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"body-offset\"></div>\r\n");
      out.write("\r\n");
      out.write("    <!--hidden parameters-->\r\n");
      out.write("    <div>\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"phoneNumberOrg\" value=\"\"/>\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"userType\" value=\"\"/>\r\n");
      out.write("   \t \t\t<input type=\"hidden\" id=\"isCompleteFlag\" value=\"0\"/>\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"showIdentifyInfo\" value=\"0\"/>\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"h_identifiedStatus\" value=\"-1\"/>\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"h_showAvaliableJoinProject\" value=\"\"/>\r\n");
      out.write("\r\n");
      out.write("   \t\t\t<input type=\"hidden\" id=\"h_category\" value=\"-1\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"isIdentifyModify\" value=\"0\"/>\r\n");
      out.write("\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"identifyStep\" value=\"1\"/>\r\n");
      out.write("   \t \t<input type=\"hidden\" id=\"identifyStatus\" value=\"-1\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!---end of hidden parameters-->\r\n");
      out.write("\r\n");
      out.write("  \t<div class=\"container\">\r\n");
      out.write("\t      <div class=\"col-lg-2 col-md-2 userInfo-left-nav\">\r\n");
      out.write("            <ul class=\"list-group userInfo-service\" id=\"userinfoNav\">\r\n");
      out.write("                <a class=\"header\">个人中心</a>\r\n");
      out.write("                  <input type=\"hidden\" id=\"tabId\" value=\"navBaseInfo\">\r\n");
      out.write("                  <input type=\"hidden\" id=\"tabContentId\" value=\"baseInfo\">\r\n");
      out.write("                \t<a class=\"list-group-item active\" id=\"navBaseInfo\" href=\"cafterlogininformation\">基本信息</a>\r\n");
      out.write("                <a class=\"list-group-item\" id=\"publishTheProject\" href=\"cpublished\">发布的项目</a>\r\n");
      out.write("<a class=\"list-group-item\" id=\"publishTheProject\" href=\"cpublish\">发布项目</a>\r\n");
      out.write("                <a class=\"list-group-item\" id=\"publishTheProject\" href=\"ccheckcontract\">我的合同</a>\r\n");
      out.write("                        </ul>\r\n");
      out.write("  \t\t  </div>\r\n");
      out.write("\r\n");
      out.write("\t\t  \t\t<div id=\"baseInfo\" class=\"col-lg-9 col-md-9 tab-form\">\r\n");
      out.write("\t\t     <form id=\"userInfoForm\" class=\"form-horizontal\" action=\"javascript:doSave()\" role=\"form\" method=\"post\">\r\n");
      out.write("\t\t     \t<div class=\"form-header\">\r\n");
      out.write("\t\t       \t\t<h3>您的基本信息</h3>\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("\t\t       <fieldset>\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t       \r\n");
      out.write("\r\n");
      out.write("\t\t       <div class=\"col-md-12 weixin\">\r\n");
      out.write("\t\t         \t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t           \t\t<label class=\"control-label form-label\" for=\"phoneNumber\"><i class=\"form-required weixinIconHidden\">*</i>手机号:</label>\r\n");
      out.write("\t\t         \t</div>\r\n");
      out.write("\t\t         \t<div class=\"col-md-8\">\r\n");
      out.write("\t\t           \t\t<div class=\"col-lg-7 col-md-7\">\r\n");
      out.write("\t\t           \t\t\t");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("</strong>\r\n");
      out.write("\t\t          \t \t\t<input type=\"text\" name=\"weixinNumber\" id=\"weixinNumber\" value=\"\" class=\"form-control form-input\"/>\r\n");
      out.write("\t\t           \t\t</div>\r\n");
      out.write("\t\t          \t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t       <div class=\"col-md-12 weixin\">\r\n");
      out.write("\t\t         \t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t           \t\t<label class=\"control-label form-label\" for=\"phoneNumber\"><i class=\"form-required weixinIconHidden\">*</i>公司名称:</label>\r\n");
      out.write("\t\t         \t</div>\r\n");
      out.write("\t\t         \t<div class=\"col-md-8\">\r\n");
      out.write("\t\t           \t\t<div class=\"col-lg-7 col-md-7\">\r\n");
      out.write("\t\t           \t\t\t");
      if (_jspx_meth_s_005fproperty_005f1(_jspx_page_context))
        return;
      out.write("</strong>\r\n");
      out.write("\t\t          \t \t\t<input type=\"text\" name=\"weixinNumber\" id=\"weixinNumber\" value=\"\" class=\"form-control form-input\"/>\r\n");
      out.write("\t\t           \t\t</div>\r\n");
      out.write("\t\t          \t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t       \r\n");
      out.write("\r\n");
      out.write("\t\t       <div class=\"col-md-12 weixin\">\r\n");
      out.write("\t\t         \t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t           \t\t<label class=\"control-label form-label\" for=\"phoneNumber\"><i class=\"form-required weixinIconHidden\">*</i>城市:</label>\r\n");
      out.write("\t\t         \t</div>\r\n");
      out.write("\t\t         \t<div class=\"col-md-8\">\r\n");
      out.write("\t\t           \t\t<div class=\"col-lg-7 col-md-7\">\r\n");
      out.write("\t\t           \t\t\t");
      if (_jspx_meth_s_005fproperty_005f2(_jspx_page_context))
        return;
      out.write("</strong>\r\n");
      out.write("\t\t          \t \t\t<input type=\"text\" name=\"weixinNumber\" id=\"weixinNumber\" value=\"\" class=\"form-control form-input\"/>\r\n");
      out.write("\t\t           \t\t</div>\r\n");
      out.write("\t\t          \t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        <div class=\"col-md-12 weixin\">\r\n");
      out.write("\t\t         \t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t           \t\t<label class=\"control-label form-label\" for=\"phoneNumber\"><i class=\"form-required weixinIconHidden\">*</i>联系人:</label>\r\n");
      out.write("\t\t         \t</div>\r\n");
      out.write("\t\t         \t<div class=\"col-md-8\">\r\n");
      out.write("\t\t           \t\t<div class=\"col-lg-7 col-md-7\">\r\n");
      out.write("\t\t           \t\t\t");
      if (_jspx_meth_s_005fproperty_005f3(_jspx_page_context))
        return;
      out.write("</strong>\r\n");
      out.write("\t\t          \t \t\t<input type=\"text\" name=\"weixinNumber\" id=\"weixinNumber\" value=\"\" class=\"form-control form-input\"/>\r\n");
      out.write("\t\t           \t\t</div>\r\n");
      out.write("\t\t          \t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        <div class=\"col-md-12 weixin\">\r\n");
      out.write("\t\t         \t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t           \t\t<label class=\"control-label form-label\" for=\"phoneNumber\"><i class=\"form-required weixinIconHidden\">*</i>联系人手机:</label>\r\n");
      out.write("\t\t         \t</div>\r\n");
      out.write("\t\t         \t<div class=\"col-md-8\">\r\n");
      out.write("\t\t           \t\t<div class=\"col-lg-7 col-md-7\">\r\n");
      out.write("\t\t           \t\t\t");
      if (_jspx_meth_s_005fproperty_005f4(_jspx_page_context))
        return;
      out.write("</strong>\r\n");
      out.write("\t\t          \t \t\t<input type=\"text\" name=\"weixinNumber\" id=\"weixinNumber\" value=\"\" class=\"form-control form-input\"/>\r\n");
      out.write("\t\t           \t\t</div>\r\n");
      out.write("\t\t          \t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t       <div class=\"col-md-12 weixin\">\r\n");
      out.write("\t\t         \t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t           \t\t<label class=\"control-label form-label\" for=\"phoneNumber\"><i class=\"form-required weixinIconHidden\">*</i>Email:</label>\r\n");
      out.write("\t\t         \t</div>\r\n");
      out.write("\t\t         \t<div class=\"col-md-8\">\r\n");
      out.write("\t\t           \t\t<div class=\"col-lg-7 col-md-7\">\r\n");
      out.write("\t\t           \t\t\t");
      if (_jspx_meth_s_005fproperty_005f5(_jspx_page_context))
        return;
      out.write("</strong>\r\n");
      out.write("\t\t          \t \t\t<input type=\"text\" name=\"weixinNumber\" id=\"weixinNumber\" value=\"\" class=\"form-control form-input\"/>\r\n");
      out.write("\t\t           \t\t</div>\r\n");
      out.write("\t\t          \t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t       <div><span id=\"vcodespan\" style=\"display: none;\"></span></div>\r\n");
      out.write("\t\t       \r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"\" id=\"baseInfo-email\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"\" id=\"baseInfo-name\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"15504638550\" id=\"baseInfo-mobile\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"0\" id=\"baseInfo-provinceId\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"0\" id=\"baseInfo-regionId\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"\" id=\"baseInfo-bankAccount\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"1\" id=\"baseInfo-userType\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"\" id=\"baseInfo-qq\"/>\r\n");
      out.write("     \t\t\t\t<input type=\"hidden\" value=\"\" id=\"baseInfo-weixin\"/>\r\n");
      out.write("\t\t\t     <br>\r\n");
      out.write("\t\t      \t <button type=\"submit\"  class=\"btn button-style col-md-2 col-md-offset-5\" style=\"margin-top:20px;\">保存</button>\r\n");
      out.write("\r\n");
      out.write("\t\t        <br>\r\n");
      out.write("\t\t       <div>\r\n");
      out.write("\t\t       \t\t<span class=\"text-left form-message-span\" style=\"display:none\" id=\"msgspan\"></span>\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \t\t\t<input type=\"hidden\" id=\"showAvaliableJoinProjectFinal\" value=\"0\">\r\n");
      out.write("\t\t\t<div id=\"canJoinTheProjectContent\" class=\"col-xs-12 col-md-9 tab-form\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t \t\t<div class=\"col-md-12\" style=\"margin-top:10px\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"col-md-12 titleDiv\">推送的项目</div>\r\n");
      out.write("\t\t\t\t \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"canJoinTheProjectItem\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t \t  <div id=\"autheninfo\" class=\"col-lg-9 col-md-9 tab-form\" style=\"display:none;\">\r\n");
      out.write("\t\t\t  \t<div>\r\n");
      out.write("\t\t\t     <form id=\"atheninfoForm\" class=\"form-horizontal\" action=\"javascript:doAthenInfoSave()\" role=\"form\" method=\"post\">\r\n");
      out.write("\t\t\t       <fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t       \t <div class=\"form-group\" id=\"userTypeChoosenDiv\">\r\n");
      out.write("\t\t\t      <div class=\"form-header\">\r\n");
      out.write("\t\t\t     \t\t\t<h3 id=\"userinfoId\"><i class=\"fa fa-paperclip\"></i>&nbsp;码客帮欢迎不同的开发力量加入,请问您的类型是？</h3>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\t            <div class=\"col-lg-10 col-md-11 col-md-offset-1\">\r\n");
      out.write("\t\t\t            \t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5 thumbnail pORc act\" id=\"personalBtn\" name=\"servicerType\" onclick=\"checkServiceType(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"personalBtnimg\" src=\"https://www.make8.com/img/user_active.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>个人</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5 col-md-offset-1 thumbnail pORc unact\" id=\"companyBtn\" name=\"servicerType\" onclick=\"checkServiceType(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"companyBtnimg\" src=\"https://www.make8.com/img/we.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>公司</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t            \t</div>\r\n");
      out.write("\t\t\t            \t<div class=\"\">\r\n");
      out.write("\t\t\t        \t\t\t<button type=\"button\" class=\"btn button-style col-md-2 col-md-offset-9\" onclick=\"nextTosecond()\">下一步 ></button>\r\n");
      out.write("\t\t\t            \t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t       </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("(function(m, ei, q, i, a, j, s) {\r\n");
      out.write("\tm[a] = m[a] || function() {\r\n");
      out.write("\t\t(m[a].a = m[a].a || []).push(arguments)\r\n");
      out.write("\t};\r\n");
      out.write("\tj = ei.createElement(q),\r\n");
      out.write("\t\ts = ei.getElementsByTagName(q)[0];\r\n");
      out.write("\tj.async = true;\r\n");
      out.write("\tj.charset = \"UTF-8\";\r\n");
      out.write("\tj.src = i + \"?v=\" + new Date().getUTCDate();\r\n");
      out.write("\ts.parentNode.insertBefore(j, s);\r\n");
      out.write("})(window, document, \"script\", \"https://www.make8.com/thirdparty/meiqia/meiqia.js?v=201608241757\", \"_MEIQIA\");\r\n");
      out.write("_MEIQIA(\"entId\", 6145);\r\n");
      out.write("// 在这里开启无按钮模式\r\n");
      out.write("_MEIQIA(\"withoutBtn\", true);\r\n");
      out.write("</script>\r\n");
      out.write("<!--start of growing io-->\r\n");
      out.write("<script type='text/javascript'>  var _vds = _vds || []; window._vds = _vds;(function(){_vds.push(['setAccountId','c6db8a4a040e48d0a6c1e0d2bfce474a']);(function() {var vds = document.createElement('script');vds.type='text/javascript';vds.async = true;vds.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'dn-growing.qbox.me/vds.js';var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(vds, s);})();})();</script>\r\n");
      out.write("<!--end of growing io-->\r\n");
      out.write("  <!--end of footer-->\r\n");
      out.write("  <!---start of help docker-->\r\n");
      out.write("  <div id=\"top\"></div>\r\n");
      out.write("  <!--end of help docker-->\r\n");
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   \t<input type=\"hidden\" id=\"topurl\" value=\"https://www.make8.com/\"/>\r\n");
      out.write("   \t<input type=\"hidden\" id=\"reload\" value=\"1\"/>\r\n");
      out.write("   \t<input type=\"hidden\" id=\"IdentifyStep\" value=\"1\"/>\r\n");
      out.write("   \t<div id=\"userInfoBase\" style=\"display: none;\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\t\t  <script type=\"text/javascript\" src=\"https://www.make8.com/js/home/userinfo.js?v=201608241757\"></script>\r\n");
      out.write("      <!--CNZZ CODE-->\r\n");
      out.write("      <div style=\"display:none;\"><script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id='cnzz_stat_icon_1257531169'%3E%3C/span%3E%3Cscript src='\" + cnzz_protocol + \"s11.cnzz.com/z_stat.php%3Fid%3D1257531169' type='text/javascript'%3E%3C/script%3E\"));</script></div>\r\n");
      out.write("     <!--END OF CNZZ CODE-->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f0_reused = false;
    try {
      _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f0.setParent(null);
      // /WEB-INF/content/cafterlogininformation.jsp(170,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f0.setValue("company.account");
      int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
      if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      _jspx_th_s_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f1_reused = false;
    try {
      _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f1.setParent(null);
      // /WEB-INF/content/cafterlogininformation.jsp(182,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f1.setValue("company.cname");
      int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
      if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      _jspx_th_s_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f2 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f2_reused = false;
    try {
      _jspx_th_s_005fproperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f2.setParent(null);
      // /WEB-INF/content/cafterlogininformation.jsp(196,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f2.setValue("company.city");
      int _jspx_eval_s_005fproperty_005f2 = _jspx_th_s_005fproperty_005f2.doStartTag();
      if (_jspx_th_s_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
      _jspx_th_s_005fproperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f2, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f3 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f3_reused = false;
    try {
      _jspx_th_s_005fproperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f3.setParent(null);
      // /WEB-INF/content/cafterlogininformation.jsp(208,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f3.setValue("company.linkman");
      int _jspx_eval_s_005fproperty_005f3 = _jspx_th_s_005fproperty_005f3.doStartTag();
      if (_jspx_th_s_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
      _jspx_th_s_005fproperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f3, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f4 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f4_reused = false;
    try {
      _jspx_th_s_005fproperty_005f4.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f4.setParent(null);
      // /WEB-INF/content/cafterlogininformation.jsp(220,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f4.setValue("company.phone");
      int _jspx_eval_s_005fproperty_005f4 = _jspx_th_s_005fproperty_005f4.doStartTag();
      if (_jspx_th_s_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
      _jspx_th_s_005fproperty_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f4, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f5 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f5_reused = false;
    try {
      _jspx_th_s_005fproperty_005f5.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f5.setParent(null);
      // /WEB-INF/content/cafterlogininformation.jsp(232,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f5.setValue("company.email");
      int _jspx_eval_s_005fproperty_005f5 = _jspx_th_s_005fproperty_005f5.doStartTag();
      if (_jspx_th_s_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
      _jspx_th_s_005fproperty_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f5, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f5_reused);
    }
    return false;
  }
}
