/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2017-12-07 07:20:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cpublish_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/java/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/qqq/WEB-INF/lib/struts2-core-2.3.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1467851796000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.30.jar", Long.valueOf(1483621054000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>发布需求 - 包满意 - 让靠谱的工程师为你开发 | 互联网软件众包平台</title>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/bootstrap.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/header.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/footer.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/comm.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/helpdocker.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/font-awesome/css/font-awesome.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jqueryvalidate/css/cmxform.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jqueryconfirm/css/jquery-confirm.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/bootstrapdialog/css/bootstrap-dialog.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jquerypagination/css/jquery.pagination.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular-route.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular-resource.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular-comm.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/map.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.placeholder.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/bootstrap.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/comm.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/footer.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/helpdocker.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/jquery.validate.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/localization/messages_zh.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryconfirm/js/jquery-confirm.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/bootstrapdialog/js/bootstrap-dialog.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery-ui.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jquerypagination/js/jquery.pagination-1.2.7.min.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/countdown/css/jquery.countdown.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/fileinput/css/fileinput.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/datetimepicker/css/bootstrap-datetimepicker.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/projectprogress.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/countdown/js/jquery.countdown.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryraty/jquery.raty.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/fileinput/js/fileinput.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/fileinput/js/fileinput_locale_zh.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/datetimepicker/js/bootstrap-datetimepicker.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/home/request.css?v=201608241757\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/style.css?v=201608241757\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/home/request.js?v=201608241757\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--start of header-->\r\n");
      out.write("\t<nav id=\"nav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a href=\"/\"> <img src=\"Images/logo.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Welcome\">首页</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"newDiv\"><a href=\"publish\">发布需求</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"projectall\">项目列表</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"stoplist\">优秀程序员</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aboutus\">关于我们</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"login_status\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"login\" class=\"btn login\" type=\"button\" onclick=\"javascript:location.href='login'\" value=\"登录\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"join\" class=\"btn join\" type=\"button\" onclick=\"javascript:location.href='register'\" value=\"注册\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!--end of header-->\r\n");
      out.write("\r\n");
      out.write("\t<!--hidden parameter-->\r\n");
      out.write("\t<input type=\"hidden\" id=\"isLoginUser\" value=\"0\"></input>\r\n");
      out.write("\t<!--end of parameter-->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"request-banner text-center\">\r\n");
      out.write("\t\t<p>Step 1 of 3</p>\r\n");
      out.write("\t\t<div class=\"request-bannerBackground\">\r\n");
      out.write("\t\t\t<div></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"breadcrumb-container-4-request\">\r\n");
      out.write("\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"col-md-offset-1 col-md-10 form\">\r\n");
      out.write("\t\t\t<!--  发布需求第一步 -->\r\n");
      out.write("\t\t\t<div id=\"requestStep1Div\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" id=\"publishRequestFormStep1\"\r\n");
      out.write("\t\t\t\t\trole=\"form\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wbm-state\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"wbm-state-tit text-center\">签署服务协议</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-center wbm-stata-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br />您的项目信息不会透露给任何第三方， <br />为确保服务质量，需要签署服务协议， <br />服务协议详细条款，<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://www.make8.com/about/contract\" target=\"_blank\">点击这里</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-offset-3 ol-xs-9 col-md-offset-5 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"agree\" id=\"agree\" onclick=\"iAgree(this)\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"wbmEp\" class=\"wbm-ep\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"checkNext()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"wbm-eo text-center\">我同意</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-xs-12 col-sm-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"next\" type=\"button\" class=\"btn btn-lg btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin-left: 0px;\" onclick=\"javascript:nextTosecond();\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"下一步\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 发布需求第二步 -->\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-1\" id=\"requestStep2Div\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none\">\r\n");
      out.write("\t\t\t\t<form action=setProjectAction class=\"form-horizontal\"\r\n");
      out.write("\t\t\t\t\tid=\"publishRequestFormStep2\" role=\"form\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center wbm-tell-name\">告诉我们您的项目</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>公司名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"projectName\" name=\"p.cname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"例如：电商类APP、网站前端开发、一个技术难点等\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>项目名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"projectName\" name=\"p.pname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"例如：电商类APP、网站前端开发、一个技术难点等\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>项目内容</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"projectName\" name=\"p.content\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"例如：电商类APP、网站前端开发、一个技术难点等\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>开始时间</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"projectName\" name=\"p.date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"例如：电商类APP、网站前端开发、一个技术难点等\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>结束时间</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"projectName\" name=\"p.dend\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"例如：电商类APP、网站前端开发、一个技术难点等\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-5 col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success wanToDo-btn wantToDo_btn_right\" type=\"submit\" class=\"btn-dark\">提交</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!--  \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"projectBudget\"><i class=\"form-required\">*</i>项目预算</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control form-control-a\" name=\"projectBudget\" id=\"projectBudget\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">项目预算</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"100-1000元\">100-1000元</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000-5000元\">1000-5000元</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5000-10000元\">5000-10000元</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1万-3万\">1万-3万</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3万-5万\">3万-5万</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5万-10万\">5万-10万</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"10万以上\">10万以上</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"待商议\">待商议</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>项目周期</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" \tdigits=true class=\"form-control form-control-a\" id=\"period\" name=\"period\" maxlength=\"3\" placeholder=\"您期望的项目交付天数\" required>\r\n");
      out.write("\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"projectType\"><i class=\"form-required\">*</i>项目类型</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"overflow: hidden;margin-top:5px ;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType1\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Andriod</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType1\" value=\"1\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType2\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>iOS</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType2\" value=\"2\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType3\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>HTML5</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType3\" value=\"3\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType4\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>网站</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType4\" value=\"4\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType5\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>微信</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType5\" value=\"5\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType7\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>UI设计</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType7\" value=\"7\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"pType8\" class=\"col-xs-6 col-md-4 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>其他</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"Type\" id=\"pType8\" value=\"8\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"projectTypeWarning\" class=\"col-md-12 checkbox-padding checkbox-warning\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t <div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"pDomainChb\">需要协助购买域名吗？</label>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"pDomainChb\" class=\"col-md-12 col-xs-12 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>需要</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"pDomainChb\" id=\"pDomainChb\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"projectType\">需要协助购买云主机和数据库吗？</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"pCloudServer\" class=\"col-md-12 col-xs-12 checkbox-padding\" onclick=\"checkboxActive(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox-img\"><img src=\"https://www.make8.com/img/checkboxchecked.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>需要</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox-display\" name=\"pCloudServer\" id=\"pCloudServer\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-group-4-textarea col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"projectDesc\"><i class=\"form-required\">*</i>填写您的需求（至少需要20个字符）</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control form-textarea\" rows=\"5\" id=\"projectDesc\" name=\"projectDesc\" placeholder=\"例如: 1. 主要功能点；2. 可参考的项目；3. 其它说明\" required=\"true\" minlength=\"20\" maxlength=\"1000\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-lg btn-default\" onclick=\"javascript:previousToFirst();\" value=\"上一步\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-lg btn-primary pull-right\" value=\"下一步\" onclick=\"javascript:nextToThird()\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--发布需求第三步 -->\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-1\" id=\"requestStep3Div\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none;\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" id=\"publishRequestFormStep3\"\r\n");
      out.write("\t\t\t\t\taction=\"javascript:doPublish();\" role=\"form\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center wbm-tell-name\">创建您的项目</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"loginName\"><i class=\"form-required\">*</i>手机号</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"loginName\" id=\"loginName\" placeholder=\"输入您的手机号\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"true\" isMobilePhoneNumber=\"true\" minlength=\"11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"11\" onkeyup=\"isJoin(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!--<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"password\"><i class=\"form-required\">*</i>验证码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\" name=\"verificationCode\" id=\"verificationCode\" minlength=\"4\" maxlength=\"4\" placeholder=\"请输入验证码\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-group-a col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\"><i class=\"form-required\">*</i>密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"password\" id=\"password\" placeholder=\"输入您的密码\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-11\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-lg btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"javascript:previousToSec();\" value=\"上一步\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-lg btn-primary pull-right\">发布</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\twindow.addEventListener(\"scroll\",navTop)\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--start of footer-->\r\n");
      out.write("\t﻿\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("(function(m, ei, q, i, a, j, s) {\r\n");
      out.write("\tm[a] = m[a] || function() {\r\n");
      out.write("\t\t(m[a].a = m[a].a || []).push(arguments)\r\n");
      out.write("\t};\r\n");
      out.write("\tj = ei.createElement(q),\r\n");
      out.write("\t\ts = ei.getElementsByTagName(q)[0];\r\n");
      out.write("\tj.async = true;\r\n");
      out.write("\tj.charset = \"UTF-8\";\r\n");
      out.write("\tj.src = i + \"?v=\" + new Date().getUTCDate();\r\n");
      out.write("\ts.parentNode.insertBefore(j, s);\r\n");
      out.write("})(window, document, \"script\", \"https://www.make8.com/thirdparty/meiqia/meiqia.js?v=201608241757\", \"_MEIQIA\");\r\n");
      out.write("_MEIQIA(\"entId\", 6145);\r\n");
      out.write("// 在这里开启无按钮模式\r\n");
      out.write("_MEIQIA(\"withoutBtn\", true);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<!--start of growing io-->\r\n");
      out.write("\t<script type='text/javascript'>  var _vds = _vds || []; window._vds = _vds;(function(){_vds.push(['setAccountId','c6db8a4a040e48d0a6c1e0d2bfce474a']);(function() {var vds = document.createElement('script');vds.type='text/javascript';vds.async = true;vds.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'dn-growing.qbox.me/vds.js';var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(vds, s);})();})();</script>\r\n");
      out.write("\t<!--end of growing io-->\r\n");
      out.write("\t<!--end of footer-->\r\n");
      out.write("\t<!---start of help docker-->\r\n");
      out.write("\t<div id=\"top\"></div>\r\n");
      out.write("\t<!--end of help docker-->\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"topurl\" value=\"https://www.make8.com/\" /> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" id=\"reload\" value=\"1\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--CNZZ CODE-->\r\n");
      out.write("\t<div style=\"display: none;\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id='cnzz_stat_icon_1257531169'%3E%3C/span%3E%3Cscript src='\" + cnzz_protocol + \"s11.cnzz.com/z_stat.php%3Fid%3D1257531169' type='text/javascript'%3E%3C/script%3E\"));</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--END OF CNZZ CODE-->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
