/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2017-12-07 02:31:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/java/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/qqq/WEB-INF/lib/struts2-core-2.3.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1467851796000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.30.jar", Long.valueOf(1483621054000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>注册 - 包满意 - 让技术大牛完成你的技术梦想 | 互联网软件众包平台</title>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/bootstrap.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/header.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/footer.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/comm.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/helpdocker.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/font-awesome/css/font-awesome.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jqueryvalidate/css/cmxform.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jqueryconfirm/css/jquery-confirm.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/bootstrapdialog/css/bootstrap-dialog.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jquerypagination/css/jquery.pagination.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular-route.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular-resource.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/angular-comm.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/map.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.placeholder.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/bootstrap.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/comm.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/footer.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/helpdocker.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/jquery.validate.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/localization/messages_zh.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryconfirm/js/jquery-confirm.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/bootstrapdialog/js/bootstrap-dialog.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery-ui.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jquerypagination/js/jquery.pagination-1.2.7.min.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/countdown/css/jquery.countdown.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/fileinput/css/fileinput.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/datetimepicker/css/bootstrap-datetimepicker.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/projectprogress.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/countdown/js/jquery.countdown.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryraty/jquery.raty.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/fileinput/js/fileinput.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/fileinput/js/fileinput_locale_zh.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/datetimepicker/js/bootstrap-datetimepicker.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/home/request.css?v=201608241757\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/style.css?v=201608241757\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/home/request.js?v=201608241757\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--start of header-->\r\n");
      out.write("\t<nav id=\"nav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a href=\"/\"> <img src=\"Images/logo.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Welcome\">首页</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"newDiv\"><a href=\"publish\">发布需求</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"projectall\">项目列表</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"stoplist\">优秀程序员</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aboutus\">关于我们</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"login_status\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"login\" class=\"btn login\" type=\"button\" onclick=\"javascript:location.href='login'\" value=\"登录\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"join\" class=\"btn join\" type=\"button\" onclick=\"javascript:location.href='register'\" value=\"注册\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!--end of header-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"breadcrumb-container-4-request\">\r\n");
      out.write("\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form action=\"cregisterAction\" method=\"get\" class=\"form-horizontal\"\r\n");
      out.write("\t\trole=\"form\">\r\n");
      out.write("\t\t<!-- <form class=\"form-horizontal\" id=\"publishRequestFormStep2\" role=\"form\" method=\"post\"> -->\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<h1 class=\"text-center wbm-tell-name\">注册</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>account</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectName\" name=\"c.account\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>password</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectDetail\" name=\"c.password\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>cname</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectDetail\" name=\"c.cname\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>city</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectDetail\" name=\"c.city\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>linkman</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectDetail\" name=\"c.linkman\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>phone</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectDetail\" name=\"c.phone\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-a col-md-9\">\r\n");
      out.write("\t\t\t\t<label for=\"projectName\"><i class=\"form-required\">*</i>email</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-a\"\r\n");
      out.write("\t\t\t\t\t\tid=\"projectDetail\" name=\"c.email\" placeholder=\"\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("\t\t\t\t<center><button type=\"submit\" class=\"btn btn-lg btn-primary pull-right\">注册</button></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
