/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2017-12-07 08:01:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class slogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/java/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/qqq/WEB-INF/lib/struts2-core-2.3.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1467851796000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.30.jar", Long.valueOf(1483621054000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>用户登录 - 码客帮 - 让靠谱的工程师为你开发 | 互联网软件众包平台</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/bootstrap.min.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/form.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/header.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://www.make8.com/css/footer-simple.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/font-awesome/css/font-awesome.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://www.make8.com/thirdparty/jqueryvalidate/css/cmxform.css?v=201608241757\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/jquery.placeholder.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/bootstrap.min.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/comm.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/jquery.validate.js?v=201608241757\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/thirdparty/jqueryvalidate/js/localization/messages_zh.js?v=201608241757\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/public/register.css?v=201608241757\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"https://www.make8.com/css/public/login.css?v=201608241757\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://www.make8.com/js/public/login.js?v=201608241757\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<!--start of header-->\r\n");
      out.write("\t<nav id=\"nav\" class=\"nav-simple\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a href=\"/\"> <img src=\"Images/logo.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Welcome\">首页</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"newDiv\"><a href=\"publish\">发布需求</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"projectall\">项目列表</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"stoplist\">优秀程序员</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aboutus\">关于我们</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"login_status\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"login\" class=\"btn login\" type=\"button\" onclick=\"javascript:location.href='login'\" value=\"登录\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"join\" class=\"btn join\" type=\"button\" onclick=\"javascript:location.href='register'\" value=\"注册\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!--end of header-->\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tclass=\"col-md-offset-1 col-xs-12 col-md-10 container join-form-marginbottom\">\r\n");
      out.write("\t\t<form id=\"loginForm\" method=\"post\" autocomplete=\"off\" role=\"form\"\r\n");
      out.write("\t\t\taction=\"sloginAction\">\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-4 col-md-4 col-lg-4 join-bg join-overflow\">\r\n");
      out.write("\t\t\t\t<div class=\"join-title-margintop\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 col-md-4 join-hr\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 col-md-4 join-title text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>登录</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 col-md-4 join-hr\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-lg-12 col-md-12 form-group-height join-phone-margintop\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-xs-10 col-lg-10 form-group form-padding-right input-bg join-overflow\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"col-xs-2 col-lg-2 span-left-bd\"><p\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-mobile-icon\"></p></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10 col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"loginName\" name=\"s.account\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-input input-color\" placeholder=\"电话\" required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tisloginnamevalid=\"true\" autocomplete=\"off\" aria-required=\"true\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-lg-10 col-xs-10 msgspan\"\r\n");
      out.write("\t\t\t\t\t\tid=\"loginNameMsg\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-md-12 form-group-height\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-xs-10 col-lg-10 form-group form-padding-right input-bg join-overflow\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"col-xs-2 col-md-2 span-left-bd\"><p\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-lock-icon\"></p></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10 col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-input input-color\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"s.password\" id=\"wpassword\" placeholder=\"密码\" minlength=\"6\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired autocomplete=\"off\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-lg-10 col-xs-10 msgspan\"\r\n");
      out.write("\t\t\t\t\t\tid=\"passwdMsg\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-md-12 form-group-height\" id=\"vcode-div\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-xs-10 col-lg-10 form-group form-padding-right input-bg\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"col-xs-2 col-md-2 span-left-bd\"><p\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-vcode-icon\"></p></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-5 col-md-5\" style=\"padding-right: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-input-small input-color\" name=\"vcode\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"vcode\" placeholder=\"验证码\" required minlength=\"4\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"4\" autocomplete=\"off\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-5 col-md-5 form-padding-right text-right\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"form-padding-right\" id=\"vcode_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/api/common/captcha\" onclick=\"refreshVCode();\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-lg-10 col-xs-10 msgspan\"\r\n");
      out.write("\t\t\t\t\t\tid=\"vcodeMsg\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--<div class=\"col-lg-4 col-md-4 col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"captcha\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"vcode_img\" src=\"/api/common/captcha\" onclick=\"refreshVCode();\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <div class=\"gou\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dagou\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"wbmEp\" class=\"wbm-ep\" onclick=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"jizhu\">记住我</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"wangji\"><a href=\"/public/find_password\">忘记密码</a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-lg-offset-1 col-xs-offset-1 col-lg-10 col-xs-10 btn-submit-container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-height\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" id=\"btnSubmit\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary btn-submit btn-submit-style\">登录</button>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"col-lg-offset-1 col-lg-10 col-xs-10 msgspan\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"loginMessage\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t没有账号?<a href=\"register\">立即注册</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--start of footer-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
