/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2017-12-07 07:18:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/java/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/qqq/WEB-INF/lib/struts2-core-2.3.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1467851796000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.30.jar", Long.valueOf(1483621054000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t <title>包满意- 让技术大牛完成你的技术梦想 | 互联网软件众包平台</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no\" />\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"包满意, 软件外包, 软件众包, 代码众包, 开发者众包, 程序员兼职, 项目外包,互联网软件外包,网站外包,安卓APP外包,Andriod APP,iOS APP外包,微信开发外包\">\r\n");
      out.write("        <meta name=\"description\" content=\"包满意是一个基于众包的互联网软件技术服务平台，建立项目需求方与技术大牛的连接。帮助需求方快速找到靠谱的软件工程师，同时也为程序员提供积累项目经验和收获财富的渠道。\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"csswlz/bootstrap.min.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"csswlz/style.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"csswlz/helpdocker.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"csswlz/font-awesome.min.css\"/>\r\n");
      out.write("\t    <link href=\"csswlz/bootstrap-dialog.min.css\"  rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"csswlz/footer.css\"/>\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--start of header-->\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<a href=\"/\">\r\n");
      out.write("\t\t\t\t<img src=\"Images/logo.png\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Welcome\">首页</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"newDiv\"><a href=\"publish\">发布需求</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"projectall\">项目列表</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"stoplist\">优秀程序员</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aboutus\">关于我们</a><div></div></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"login_status\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"login\" class=\"btn login\" type=\"button\" onclick=\"javascript:location.href='login'\" value=\"登录\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"join\" class=\"btn join\" type=\"button\" onclick=\"javascript:location.href='register'\" value=\"注册\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t   </ul>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!--end of header-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-12 headImg\">\r\n");
      out.write("\t\t\t<div class=\"container text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 head-Font-bg\">让技术大牛完成你的技术梦想</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 head-Font-sm\"> 更低的成本  | 更高的开发质量</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<input id=\"Send\" type=\"button\" class=\"btn Send\" onclick=\"javascript:location.href='publish'\" value=\"发布需求\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<div class=\"col-md-12 padding wantToDo\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-6 hidden-xs wantToDo_bg\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-md-6 text-center wanToDo-Div\">\r\n");
      out.write("\t\t\t\t\t\t<p>您有一个需求？</p>\r\n");
      out.write("\t\t\t\t\t\t<img style=\"display: block;margin: 0 auto;\" src=\"https://static.make8.com/img/v2/demand.png\" />\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary wanToDo-btn wantToDo_btn_left\" onclick=\"javascript:window.location.href='publish'\">发布需求</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-md-6 text-center wanToDo-Div\">\r\n");
      out.write("\t\t\t\t\t\t<p>您是技术大牛？</p>\r\n");
      out.write("\t\t\t\t\t\t<img style=\"display: block;margin: 0 auto;\" src=\"https://static.make8.com/img/v2/technology.png\" />\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success wanToDo-btn wantToDo_btn_right\" onclick=\"javascript:window.location.href='sregister'\">认证码客</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-12 data\">\r\n");
      out.write("\t\t\t<div class=\"container text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-4 data-div\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-4 data-div\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("﻿\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("(function(m, ei, q, i, a, j, s) {\r\n");
      out.write("\tm[a] = m[a] || function() {\r\n");
      out.write("\t\t(m[a].a = m[a].a || []).push(arguments)\r\n");
      out.write("\t};\r\n");
      out.write("\tj = ei.createElement(q),\r\n");
      out.write("\t\ts = ei.getElementsByTagName(q)[0];\r\n");
      out.write("\tj.async = true;\r\n");
      out.write("\tj.charset = \"UTF-8\";\r\n");
      out.write("\tj.src = i + \"?v=\" + new Date().getUTCDate();\r\n");
      out.write("\ts.parentNode.insertBefore(j, s);\r\n");
      out.write("})(window, document, \"script\", \"https://www.make8.com/thirdparty/meiqia/meiqia.js?v=201608241757\", \"_MEIQIA\");\r\n");
      out.write("_MEIQIA(\"entId\", 6145);\r\n");
      out.write("// 在这里开启无按钮模式\r\n");
      out.write("_MEIQIA(\"withoutBtn\", true);\r\n");
      out.write("</script>\r\n");
      out.write("<!--start of growing io-->\r\n");
      out.write("<script type='text/javascript'>  var _vds = _vds || []; window._vds = _vds;(function(){_vds.push(['setAccountId','c6db8a4a040e48d0a6c1e0d2bfce474a']);(function() {var vds = document.createElement('script');vds.type='text/javascript';vds.async = true;vds.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'dn-growing.qbox.me/vds.js';var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(vds, s);})();})();</script>\r\n");
      out.write("<!--end of growing io-->\r\n");
      out.write("\t\t\t\t<!--end of footer-->\r\n");
      out.write("\t\t\t\t<!---start of help docker-->\r\n");
      out.write("\t\t\t\t<div id=\"top\"></div>\r\n");
      out.write("\t\t\t\t<!--end of help docker-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"topurl\" value=\"https://www.make8.com/\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"reload\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"version\" value=\"201608241757\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--CNZZ CODE-->\r\n");
      out.write("\t\t\t\t<div style=\"display:none;\"><script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id='cnzz_stat_icon_1257531169'%3E%3C/span%3E%3Cscript src='\" + cnzz_protocol + \"s11.cnzz.com/z_stat.php%3Fid%3D1257531169' type='text/javascript'%3E%3C/script%3E\"));</script></div>\r\n");
      out.write("\t\t\t\t<!--END OF CNZZ CODE-->\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
